# Site Settings
title: Zackery Wilson | Software Engineer and Web Developer
email: zackazt@gmail.com
description: Software engineering, web development, mobile and app development, Android, iOS, and general Computer Science topics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.zwilsondev.com" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
author_image: "/zwilson.jpg"

# User Settings
username: ZackAZT
user_description: Software Engineer and Web Developer
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: zackazt
twitter_username: TheZackAZT
instagram_username: zackazt
linkedin_username: zackazt

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
